# SPDX-FileCopyrightText: 2024 Cédric Bosdonnat <cedric.bosdonnat@gmail.com>
#
# SPDX-License-Identifier: MIT

name: Run-Daily

on:
  schedule:
    - cron: '30 16 * * *'
  push:
    branches:
      - organic-maps
  pull_request:
    branches:
      - organic-maps

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5 

    - name: Generate the files
      run: |
        python3 fr.py -o out/fr
        python3 es.py -o out/es
        python3 it.py -o out/it
        cp -r docs/* out/
        echo "## fr" >> out/README.md
        echo "" >> out/README.md
        for f in `ls -1 out/fr`; do
          echo "* [$f](fr/$f)" >> out/README.md
        done
        echo "## es" >> out/README.md
        echo "" >> out/README.md
        for f in `ls -1 out/es`; do
          echo "* [$f](es/$f)" >> out/README.md
        done
        echo "## it" >> out/README.md
        echo "" >> out/README.md
        for f in `ls -1 out/it`; do
          echo "* [$f](it/$f)" >> out/README.md
        done
        echo out/README.md

    - name: Build site with Jekyll
      uses: actions/jekyll-build-pages@v1
      with:
        source: out

    - name: Upload files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./_site

  deploy:
    needs: run
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} 
    
    steps:
    - name: Deploy to github pages
      id: deployment
      uses: actions/deploy-pages@v5

